import re
from typing import Literal, Optional, List, Dict, Any, Union
from pydantic import BaseModel, Field, field_validator


class BoundingBox(BaseModel):
    min_lon: float
    min_lat: float
    max_lon: float
    max_lat: float

    def to_list(self) -> List[float]:
        return [self.min_lon, self.min_lat, self.max_lon, self.max_lat]


class GeoJSONGeometry(BaseModel):
    type: Literal["Polygon", "MultiPolygon", "Point", "LineString", "Feature", "FeatureCollection"] = "Polygon"
    coordinates: Any
    properties: Optional[Dict[str, Any]] = None


class QueryRequest(BaseModel):
    """User input natural language query payload with optional explicit AOI."""
    text: str = Field(..., description="Natural language query string")
    aoi_geometry: Optional[Union[Dict[str, Any], GeoJSONGeometry]] = Field(
        default=None,
        description="Optional GeoJSON Polygon or Feature drawn on the frontend map"
    )
    bbox: Optional[Union[List[float], BoundingBox]] = Field(
        default=None,
        description="Optional explicit bounding box [min_lon, min_lat, max_lon, max_lat]"
    )


class DirectAOIAnalysisRequest(BaseModel):
    """Direct analysis endpoint payload for frontend map drawn shapes."""
    aoi_geometry: Optional[Union[Dict[str, Any], GeoJSONGeometry]] = Field(
        default=None,
        description="GeoJSON Polygon, MultiPolygon or Feature"
    )
    bbox: Optional[List[float]] = Field(
        default=None,
        description="[min_lon, min_lat, max_lon, max_lat] in EPSG:4326"
    )
    start_date: str = Field(..., description="Start date in YYYY-MM-DD")
    end_date: str = Field(..., description="End date in YYYY-MM-DD")
    max_cloud_cover: float = Field(default=100.0, description="Max scene cloud cover percentage (0-100)")
    cloud_mask: bool = Field(default=True, description="Apply SCL cloud screening")
    analysis_type: Literal["ndvi", "ndwi", "ndvi-ndwi", "change_detection"] = "ndvi"
    # Secondary period for change detection
    comparison_start_date: Optional[str] = None
    comparison_end_date: Optional[str] = None


class StructuredQuery(BaseModel):
    """
    Extracted structured parameters from Gemini LLM.
    Strictly focuses on intent and constraints without performing geospatial math.
    """
    location: Optional[str] = Field(default=None, description="The place name or location mentioned")
    start_date: Optional[str] = Field(default=None, description="Start date in YYYY-MM-DD")
    end_date: Optional[str] = Field(default=None, description="End date in YYYY-MM-DD")
    dataset: str = Field(default="sentinel-2-l2a", description="Dataset identifier")
    cloud_cover_max: Optional[float] = Field(default=None, description="Max cloud cover percentage (0-100)")
    analysis_type: Optional[Literal[
        "ndvi",
        "ndwi",
        "ndvi-ndwi",
        "weather",
        "change_detection",
        "search"
    ]] = Field(default=None, description="Type of analysis requested")
    requested_index: Optional[str] = Field(default=None, description="Specific index like NDVI, NDWI, etc.")
    bands: List[str] = Field(default_factory=list, description="Specific satellite bands required")
    aoi_required: bool = Field(default=False, description="Whether an Area of Interest is required")
    is_temporal_comparison: bool = Field(default=False, description="Whether the user requested a temporal comparison")
    comparison_start_date: Optional[str] = None
    comparison_end_date: Optional[str] = None
    query_type: Literal[
        "data_search",
        "analysis",
        "comparison"
    ] = Field(default="analysis", description="High-level category of the query")

    @field_validator('cloud_cover_max')
    def validate_cloud_cover(cls, v):
        if v is not None:
            if v < 0 or v > 100:
                raise ValueError('Cloud cover must be between 0 and 100')
        return v

    @field_validator('start_date', 'end_date', 'comparison_start_date', 'comparison_end_date')
    def validate_date_format(cls, v):
        if v is not None:
            if not re.match(r'^\d{4}-\d{2}-\d{2}$', v):
                raise ValueError(f"Date '{v}' must be in YYYY-MM-DD format")
        return v


class QueryPlan(BaseModel):
    """
    Deterministic plan generated by the Query Planner.
    Specifies exact coordinates, bounding boxes, polygon geometries, date ranges, and parameters.
    """
    latitude: float
    longitude: float
    location_name: str
    bbox: Optional[BoundingBox] = None
    aoi_geometry: Optional[Dict[str, Any]] = None
    has_polygon_aoi: bool = False
    start_date: str
    end_date: str
    cloud_cover_max: float = 10.0
    analysis_type: str = "ndvi"
    dataset: str = "sentinel-2-l2a"
    bands: List[str] = Field(default_factory=list)
    aoi_required: bool = False
    query_type: str = "analysis"
    is_temporal_comparison: bool = False
    comparison_start_date: Optional[str] = None
    comparison_end_date: Optional[str] = None
    parameters: Dict[str, Any] = Field(default_factory=dict)


# For backward compatibility with existing CompiledQuery references
CompiledQuery = QueryPlan
